### ISSUE TITLE
Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $

### ISSUE THREAD

**Issue by YXxy1002** [dromara/shenyu#1481] opened 2021-05-17 11:46 UTC
i have two client, but the selector data is different, and one of it will produce JSON parse error
![image](https://user-images.githubusercontent.com/36941654/118483074-2e76d480-b748-11eb-8c2a-0d4b2ab3bcd0.png)
![image](https://user-images.githubusercontent.com/36941654/118483090-33d41f00-b748-11eb-8682-37e0e5f01dec.png)
![image](https://user-images.githubusercontent.com/36941654/118483350-7bf34180-b748-11eb-9a86-6b8c3c82e0ce.png)
![image](https://user-images.githubusercontent.com/36941654/118483435-95948900-b748-11eb-84af-d1c5b3631dce.png)

**Comment by SaberSola** [comment] 2021-05-17 12:10
I think it may be a bug....

**Comment by SaberSola** [comment] 2021-05-17 12:17
Can you provide more detailed stack information

**Comment by YXxy1002** [comment] 2021-05-17 12:53
this code modified the selector handle data
![image](https://user-images.githubusercontent.com/36941654/118491487-a1d11400-b751-11eb-8e27-23fb1dbc5c28.png)

`Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.6.jar:?]
	at org.dromara.soul.common.utils.GsonUtils.fromJson(GsonUtils.java:110) ~[soul-common-2.3.0-RELEASE.jar:2.3.0-RELEASE]
	at org.dromara.soul.plugin.springcloud.SpringCloudPlugin.doExecute(SpringCloudPlugin.java:71) ~[soul-plugin-springcloud-2.3.0-RELEASE.jar:2.3.0-RELEASE]
	at org.dromara.soul.plugin.base.AbstractSoulPlugin.execute(AbstractSoulPlugin.java:95) ~[soul-plugin-base-2.3.0-RELEASE.jar:2.3.0-RELEASE]
	at org.dromara.soul.web.handler.SoulWebHandler$DefaultSoulPluginChain.lambda$execute$0(SoulWebHandler.java:100) ~[soul-web-2.3.0-RELEASE.jar:2.3.0-RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) [reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213) [reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:124) [reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
`

**Comment by YXxy1002** [comment] 2021-05-17 12:54
@SaberSola

**Comment by SaberSola** [comment] 2021-05-17 13:38
This handle belongs to divide plugin,Why it is Id 8

**Comment by SaberSola** [comment] 2021-05-17 14:16
This is a bug, It has been fixed in the master branch

**Comment by SaberSola** [comment] 2021-05-17 14:24
![image](https://user-images.githubusercontent.com/24998393/118505033-9e905500-b75e-11eb-8752-dfae67c72bdb.png)
The judgment is reversed

**Comment by dengliming** [comment] 2021-05-17 14:57
Duplicate of [https://github.com/dromara/shenyu/issues/1297](https://github.com/dromara/shenyu/issues/1297), Already fixed by [https://github.com/dromara/shenyu/pull/1315](https://github.com/dromara/shenyu/pull/1315)

**Closed by dengliming** 2021-05-17 14:57 UTC
Labels: type: question
